quarkus:
  http:
    port: 8080
  container-image:
    build: true
    builder: docker
  native:
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:21.3-java21

resources:
  ai:
    neural-network:
      evaluate-every-n-epochs: 150
      log-every-n-epochs: 300

      label-index: 0
      learning-rate: 0.001
      regularizationL2: 0.0001
      num-classes: 1
      num-in: 3
      num-out: 1
      num-epochs: 10000
      batch-size: 64
      hidden-layers-neurons: 75

  deka:
    # Data
    csv-file: src/main/resources/deka/financeDeka.csv

    # Model Files
    neural-network:
      model: src/main/resources/deka/AIModelDeka.bin
      best-model: src/main/resources/deka/bestModelDeka.bin
      # Data Chart
      chart-file: src/main/resources/deka/AIModelTrainedDeka.png

    regression:
      degree: 3
      function-file: src/main/resources/deka/regressionDeka.ser
      # Data Chart
      chart-file: src/main/resources/deka/regressionFunctionDeka.png

  btc:
    # Data
    csv-file: src/main/resources/btc/financeBTC.csv

    # Model Files
    neural-network:
      model: src/main/resources/btc/AIModelBTC.bin
      best-model: src/main/resources/btc/bestModelBTC.bin
      # Data Chart
      chart-file: src/main/resources/btc/AIModelTrainedBTC.png

    regression:
      degree: 20
      function-file: src/main/resources/btc/regressionBTC.ser
      # Data Chart
      chart-file: src/main/resources/btc/regressionFunctionBTC.png